# Generated by Django 3.1.5 on 2021-07-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addhotelstep2',
            old_name='hotel_name',
            new_name='hotel_name_2',
        ),
        migrations.CreateModel(
            name='SingleRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_room_name', models.TextField(choices=[('Budget_single_room', 'Budget Single Room'), ('Standard_single_room', 'Standard Single Room'), ('Superior_single_room', 'Superior Single Room'), ('Deluxe_single_room', 'Deluxe Single Room')], max_length=30)),
                ('smoke', models.TextField(choices=[('Smoking', 'Smoking'), ('Non-Smoking', 'Non-Smoking')], max_length=15)),
                ('room_size', models.IntegerField()),
                ('hotel_name_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.addhotelstep2')),
            ],
        ),
        migrations.CreateModel(
            name='DoubleRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('double_room_name', models.TextField(choices=[('Budget_Double_room', 'Budget Double Room'), ('Standard_Double_room', 'Standard Double Room'), ('Superior_Double_room', 'Superior Double Room'), ('Deluxe_Double_room', 'Deluxe Double Room')], max_length=30)),
                ('smoke', models.TextField(choices=[('Smoking', 'Smoking'), ('Non-Smoking', 'Non-Smoking')], max_length=15)),
                ('single_bed_size', models.TextField(choices=[('Single_bed_90_130_1', 'Single Bed / 90-130 cm wide / 1 quantity'), ('Single_bed_90_130_2', 'Single Bed / 90-130 cm wide / 2 quantity'), ('Single_bed_90_130_3', 'Single Bed / 90-130 cm wide / 3 quantity'), ('Single_bed_90_130_4', 'Single Bed / 90-130 cm wide / 4 quantity'), ('Single_bed_90_130_5', 'Single Bed / 90-130 cm wide / 5 quantity')])),
                ('double_bed_size', models.TextField(choices=[('Double_bed_131_150_1', 'Double Bed / 131-150 cm wide / 1 quantity'), ('Double_bed_131_150_2', 'Double Bed / 131-150 cm wide / 2 quantity'), ('Double_bed_131_150_3', 'Double Bed / 131-150 cm wide / 3 quantity'), ('Double_bed_131_150_4', 'Double Bed / 131-150 cm wide / 4 quantity'), ('Double_bed_131_150_5', 'Double Bed / 131-150 cm wide / 5 quantity')])),
                ('large_bed_size', models.TextField(choices=[('Large_bed_king_size_151_180_1', 'Large Bed (King Size) / 151-180 cm wide / 1 quantity'), ('Large_bed_king_size_151_180_2', 'Large Bed (King Size) / 151-180 cm wide / 2 quantity'), ('Large_bed_king_size_151_180_3', 'Large Bed (King Size) / 151-180 cm wide / 3 quantity'), ('Large_bed_king_size_151_180_4', 'Large Bed (King Size) / 151-180 cm wide / 4 quantity'), ('Large_bed_king_size_151_180_5', 'Large Bed (King Size) / 151-180 cm wide / 5 quantity')])),
                ('capacity', models.IntegerField()),
                ('room_size', models.IntegerField()),
                ('hotel_name_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.addhotelstep2')),
            ],
        ),
    ]
